language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "4"
  - "6"

script:
  - npm run tslint
  - npm run test
  - npm run cover
  - npm run build

before_script:
  - mkdir -p reports

after_script:
  - npm install coveralls
  - cat ./reports/lcov.info | ./node_modules/coveralls/bin/coveralls.js
